### ISSUE TITLE
Fails to build on FreeBSD 13.0-RELEASE

### ISSUE THREAD

**Issue by probonopd** [3dproger/LazyComposer#12]
Fails to build on FreeBSD 13.0-RELEASE:

```
clang++ -pthread -Wl,-rpath,/usr/local/lib/qt5 -o LazyComposer QMidiOut.o QMidiFile.o QMidiIn.o main.o mainwindow.o midi.o midistorage.o midiplayer.o composer.o windowmidistructure.o patternstorage.o qrc_resources.o qrc_qmake_qmake_qm_files.o moc_QMidiIn.o moc_mainwindow.o moc_midi.o moc_midistorage.o moc_midiplayer.o moc_composer.o moc_windowmidistructure.o moc_patternstorage.o   -L/usr/local/lib /usr/local/lib/qt5/libQt5Widgets.so /usr/local/lib/qt5/libQt5Gui.so /usr/local/lib/qt5/libQt5Core.so -lGL   
/usr/local/bin/x86_64-unknown-freebsd13.0-ld: QMidiOut.o: in function `QMidiOut::~QMidiOut()':
QMidiOut.cpp:(.text+0x34): undefined reference to `QMidiOut::disconnect()'
/usr/local/bin/x86_64-unknown-freebsd13.0-ld: QMidiOut.o: in function `QMidiOut::sendEvent(QMidiEvent const&)':
QMidiOut.cpp:(.text+0xad): undefined reference to `QMidiOut::sendSysEx(QByteArray const&)'
/usr/local/bin/x86_64-unknown-freebsd13.0-ld: QMidiOut.cpp:(.text+0xf4): undefined reference to `QMidiOut::sendMsg(int)'
/usr/local/bin/x86_64-unknown-freebsd13.0-ld: QMidiOut.o: in function `QMidiOut::setInstrument(int, int)':
QMidiOut.cpp:(.text+0x141): undefined reference to `QMidiOut::sendMsg(int)'
/usr/local/bin/x86_64-unknown-freebsd13.0-ld: QMidiOut.o: in function `QMidiOut::noteOn(int, int, int)':
QMidiOut.cpp:(.text+0x166): undefined reference to `QMidiOut::sendMsg(int)'
/usr/local/bin/x86_64-unknown-freebsd13.0-ld: QMidiOut.o: in function `QMidiOut::noteOff(int, int, int)':
QMidiOut.cpp:(.text+0x186): undefined reference to `QMidiOut::sendMsg(int)'
/usr/local/bin/x86_64-unknown-freebsd13.0-ld: QMidiOut.o: in function `QMidiOut::pitchWheel(int, int)':
QMidiOut.cpp:(.text+0x1b6): undefined reference to `QMidiOut::sendMsg(int)'
/usr/local/bin/x86_64-unknown-freebsd13.0-ld: QMidiOut.o:QMidiOut.cpp:(.text+0x1d1): more undefined references to `QMidiOut::sendMsg(int)' follow
/usr/local/bin/x86_64-unknown-freebsd13.0-ld: QMidiIn.o: in function `QMidiIn::~QMidiIn()':
QMidiIn.cpp:(.text+0x62): undefined reference to `QMidiIn::disconnect()'
/usr/local/bin/x86_64-unknown-freebsd13.0-ld: midi.o: in function `Midi::Midi(QObject*)':
midi.cpp:(.text+0xb4): undefined reference to `QMidiOut::devices()'
/usr/local/bin/x86_64-unknown-freebsd13.0-ld: midi.cpp:(.text+0x5fb): undefined reference to `QMidiOut::connect(QString)'
/usr/local/bin/x86_64-unknown-freebsd13.0-ld: midi.o: in function `Midi::~Midi()':
midi.cpp:(.text+0xbd3): undefined reference to `QMidiOut::disconnect()'
/usr/local/bin/x86_64-unknown-freebsd13.0-ld: midiplayer.o: in function `MidiPlayer::devices() const':
midiplayer.cpp:(.text+0x958): undefined reference to `QMidiOut::devices()'
/usr/local/bin/x86_64-unknown-freebsd13.0-ld: midiplayer.o: in function `MidiPlayer::setDevice(QString const&)':
midiplayer.cpp:(.text+0x1293): undefined reference to `QMidiOut::disconnect()'
/usr/local/bin/x86_64-unknown-freebsd13.0-ld: midiplayer.cpp:(.text+0x19cf): undefined reference to `QMidiOut::connect(QString)'
/usr/local/bin/x86_64-unknown-freebsd13.0-ld: midiplayer.o: in function `MidiPlayer::~MidiPlayer()':
midiplayer.cpp:(.text+0x23fc): undefined reference to `QMidiOut::disconnect()'
/usr/local/bin/x86_64-unknown-freebsd13.0-ld: midiplayer.o: in function `MidiPlayer::run()':
midiplayer.cpp:(.text+0x2982): undefined reference to `QMidiOut::sendMsg(int)'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile:389: LazyComposer] Fehler 1
```
